[build]
  base = "/"  # Set the base directory to the root
  command = "npm run build"  # Run npm build directly without changing directories
  publish = "public"  # Specify the directory from which files will be deployed
  functions = "netlify/functions"  # Specify the directory for Netlify Functions  
  environment = { PHP_VERSION = "8.0" }



