[build]
  base = "/"  # Set the base directory to the root
  command = "cd public && npm run build"  # Change directory to public and then run npm build
  publish = "public"  # Specify the directory from which files will be deployed
  functions = "public/netlify/functions"  # Specify the directory for Netlify Functions
  environment = { PHP_VERSION = "8.0" }

[context.production]
  base = "/"
  publish = "public" # Update to your correct publish directory

[context.deploy-preview]
  base = "/"
  publish = "public" # Update to your correct directory



